// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWzVUFC-EV9RmV2JJYZrRq7FthyGyINCM',
    appId: '1:318936429177:web:78581edeb47e7e150c1aa8',
    messagingSenderId: '318936429177',
    projectId: 'austism3030',
    authDomain: 'austism3030.firebaseapp.com',
    storageBucket: 'austism3030.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpRlH3RqaUmLfDc9scg2OQAQOxeUFRthk',
    appId: '1:318936429177:android:87658f2e905fbe770c1aa8',
    messagingSenderId: '318936429177',
    projectId: 'austism3030',
    storageBucket: 'austism3030.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcCM-LWiPK26eNJeUT5_NQdFYzccF0Xpo',
    appId: '1:318936429177:ios:8cbae83408cb6bc50c1aa8',
    messagingSenderId: '318936429177',
    projectId: 'austism3030',
    storageBucket: 'austism3030.appspot.com',
    iosBundleId: 'com.example.austism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcCM-LWiPK26eNJeUT5_NQdFYzccF0Xpo',
    appId: '1:318936429177:ios:8cbae83408cb6bc50c1aa8',
    messagingSenderId: '318936429177',
    projectId: 'austism3030',
    storageBucket: 'austism3030.appspot.com',
    iosBundleId: 'com.example.austism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWzVUFC-EV9RmV2JJYZrRq7FthyGyINCM',
    appId: '1:318936429177:web:8d1d838bc4431e6b0c1aa8',
    messagingSenderId: '318936429177',
    projectId: 'austism3030',
    authDomain: 'austism3030.firebaseapp.com',
    storageBucket: 'austism3030.appspot.com',
  );
}
